/*
 * This file is generated by jOOQ.
 */
package ru.onko.model.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;

import ru.onko.model.jooq.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum AccountState implements EnumType {

    NOT_CONFIRMED("NOT_CONFIRMED"),

    CONFIRMED("CONFIRMED"),

    DELETED("DELETED");

    private final String literal;

    private AccountState(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "account_state";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static AccountState lookupLiteral(String literal) {
        return EnumType.lookupLiteral(AccountState.class, literal);
    }
}
