/*
 * This file is generated by jOOQ.
 */
package ru.onko.model.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;

import ru.onko.model.jooq.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Gender implements EnumType {

    MALE("MALE"),

    FEMALE("FEMALE");

    private final String literal;

    private Gender(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "gender";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static Gender lookupLiteral(String literal) {
        return EnumType.lookupLiteral(Gender.class, literal);
    }
}
