/*
 * This file is generated by jOOQ.
 */
package ru.onko.model.jooq.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.onko.model.jooq.tables.ArticlePhotos;
import ru.onko.model.jooq.tables.pojos.ArticlePhotosEntity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticlePhotosRecord extends UpdatableRecordImpl<ArticlePhotosRecord> implements Record2<UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.article_photos.article_id</code>.
     */
    public void setArticleId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.article_photos.article_id</code>.
     */
    public UUID getArticleId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.article_photos.photo_id</code>.
     */
    public void setPhotoId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.article_photos.photo_id</code>.
     */
    public UUID getPhotoId() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return ArticlePhotos.ARTICLE_PHOTOS_ENTITY.ARTICLE_ID;
    }

    @Override
    public Field<UUID> field2() {
        return ArticlePhotos.ARTICLE_PHOTOS_ENTITY.PHOTO_ID;
    }

    @Override
    public UUID component1() {
        return getArticleId();
    }

    @Override
    public UUID component2() {
        return getPhotoId();
    }

    @Override
    public UUID value1() {
        return getArticleId();
    }

    @Override
    public UUID value2() {
        return getPhotoId();
    }

    @Override
    public ArticlePhotosRecord value1(UUID value) {
        setArticleId(value);
        return this;
    }

    @Override
    public ArticlePhotosRecord value2(UUID value) {
        setPhotoId(value);
        return this;
    }

    @Override
    public ArticlePhotosRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticlePhotosRecord
     */
    public ArticlePhotosRecord() {
        super(ArticlePhotos.ARTICLE_PHOTOS_ENTITY);
    }

    /**
     * Create a detached, initialised ArticlePhotosRecord
     */
    public ArticlePhotosRecord(UUID articleId, UUID photoId) {
        super(ArticlePhotos.ARTICLE_PHOTOS_ENTITY);

        setArticleId(articleId);
        setPhotoId(photoId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ArticlePhotosRecord
     */
    public ArticlePhotosRecord(ArticlePhotosEntity value) {
        super(ArticlePhotos.ARTICLE_PHOTOS_ENTITY);

        if (value != null) {
            setArticleId(value.getArticleId());
            setPhotoId(value.getPhotoId());
            resetChangedOnNotNull();
        }
    }
}
