/*
 * This file is generated by jOOQ.
 */
package ru.onko.model.jooq.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import ru.onko.model.jooq.tables.Article;
import ru.onko.model.jooq.tables.pojos.ArticleEntity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleRecord extends UpdatableRecordImpl<ArticleRecord> implements Record5<UUID, String, String, UUID, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.article.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.article.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.article.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.article.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.article.content</code>.
     */
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.article.content</code>.
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.article.account_id</code>.
     */
    public void setAccountId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.article.account_id</code>.
     */
    public UUID getAccountId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.article.position</code>.
     */
    public void setPosition(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.article.position</code>.
     */
    public String getPosition() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, String, String, UUID, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, String, String, UUID, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Article.ARTICLE_ENTITY.ID;
    }

    @Override
    public Field<String> field2() {
        return Article.ARTICLE_ENTITY.TITLE;
    }

    @Override
    public Field<String> field3() {
        return Article.ARTICLE_ENTITY.CONTENT;
    }

    @Override
    public Field<UUID> field4() {
        return Article.ARTICLE_ENTITY.ACCOUNT_ID;
    }

    @Override
    public Field<String> field5() {
        return Article.ARTICLE_ENTITY.POSITION;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getContent();
    }

    @Override
    public UUID component4() {
        return getAccountId();
    }

    @Override
    public String component5() {
        return getPosition();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getContent();
    }

    @Override
    public UUID value4() {
        return getAccountId();
    }

    @Override
    public String value5() {
        return getPosition();
    }

    @Override
    public ArticleRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ArticleRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public ArticleRecord value3(String value) {
        setContent(value);
        return this;
    }

    @Override
    public ArticleRecord value4(UUID value) {
        setAccountId(value);
        return this;
    }

    @Override
    public ArticleRecord value5(String value) {
        setPosition(value);
        return this;
    }

    @Override
    public ArticleRecord values(UUID value1, String value2, String value3, UUID value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleRecord
     */
    public ArticleRecord() {
        super(Article.ARTICLE_ENTITY);
    }

    /**
     * Create a detached, initialised ArticleRecord
     */
    public ArticleRecord(UUID id, String title, String content, UUID accountId, String position) {
        super(Article.ARTICLE_ENTITY);

        setId(id);
        setTitle(title);
        setContent(content);
        setAccountId(accountId);
        setPosition(position);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ArticleRecord
     */
    public ArticleRecord(ArticleEntity value) {
        super(Article.ARTICLE_ENTITY);

        if (value != null) {
            setId(value.getId());
            setTitle(value.getTitle());
            setContent(value.getContent());
            setAccountId(value.getAccountId());
            setPosition(value.getPosition());
            resetChangedOnNotNull();
        }
    }
}
