/*
 * This file is generated by jOOQ.
 */
package ru.onko.model.jooq.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.onko.model.jooq.tables.FavoriteArticles;
import ru.onko.model.jooq.tables.pojos.FavoriteArticlesEntity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FavoriteArticlesRecord extends UpdatableRecordImpl<FavoriteArticlesRecord> implements Record2<UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.favorite_articles.account_id</code>.
     */
    public void setAccountId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.favorite_articles.account_id</code>.
     */
    public UUID getAccountId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.favorite_articles.article_id</code>.
     */
    public void setArticleId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.favorite_articles.article_id</code>.
     */
    public UUID getArticleId() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return FavoriteArticles.FAVORITE_ARTICLES_ENTITY.ACCOUNT_ID;
    }

    @Override
    public Field<UUID> field2() {
        return FavoriteArticles.FAVORITE_ARTICLES_ENTITY.ARTICLE_ID;
    }

    @Override
    public UUID component1() {
        return getAccountId();
    }

    @Override
    public UUID component2() {
        return getArticleId();
    }

    @Override
    public UUID value1() {
        return getAccountId();
    }

    @Override
    public UUID value2() {
        return getArticleId();
    }

    @Override
    public FavoriteArticlesRecord value1(UUID value) {
        setAccountId(value);
        return this;
    }

    @Override
    public FavoriteArticlesRecord value2(UUID value) {
        setArticleId(value);
        return this;
    }

    @Override
    public FavoriteArticlesRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FavoriteArticlesRecord
     */
    public FavoriteArticlesRecord() {
        super(FavoriteArticles.FAVORITE_ARTICLES_ENTITY);
    }

    /**
     * Create a detached, initialised FavoriteArticlesRecord
     */
    public FavoriteArticlesRecord(UUID accountId, UUID articleId) {
        super(FavoriteArticles.FAVORITE_ARTICLES_ENTITY);

        setAccountId(accountId);
        setArticleId(articleId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FavoriteArticlesRecord
     */
    public FavoriteArticlesRecord(FavoriteArticlesEntity value) {
        super(FavoriteArticles.FAVORITE_ARTICLES_ENTITY);

        if (value != null) {
            setAccountId(value.getAccountId());
            setArticleId(value.getArticleId());
            resetChangedOnNotNull();
        }
    }
}
