/*
 * This file is generated by jOOQ.
 */
package ru.onko.model.jooq.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.onko.model.jooq.tables.NotesTags;
import ru.onko.model.jooq.tables.pojos.NotesTagsEntity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotesTagsRecord extends UpdatableRecordImpl<NotesTagsRecord> implements Record2<UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.notes_tags.note_id</code>.
     */
    public void setNoteId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.notes_tags.note_id</code>.
     */
    public UUID getNoteId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.notes_tags.tag_id</code>.
     */
    public void setTagId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.notes_tags.tag_id</code>.
     */
    public UUID getTagId() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return NotesTags.NOTES_TAGS_ENTITY.NOTE_ID;
    }

    @Override
    public Field<UUID> field2() {
        return NotesTags.NOTES_TAGS_ENTITY.TAG_ID;
    }

    @Override
    public UUID component1() {
        return getNoteId();
    }

    @Override
    public UUID component2() {
        return getTagId();
    }

    @Override
    public UUID value1() {
        return getNoteId();
    }

    @Override
    public UUID value2() {
        return getTagId();
    }

    @Override
    public NotesTagsRecord value1(UUID value) {
        setNoteId(value);
        return this;
    }

    @Override
    public NotesTagsRecord value2(UUID value) {
        setTagId(value);
        return this;
    }

    @Override
    public NotesTagsRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotesTagsRecord
     */
    public NotesTagsRecord() {
        super(NotesTags.NOTES_TAGS_ENTITY);
    }

    /**
     * Create a detached, initialised NotesTagsRecord
     */
    public NotesTagsRecord(UUID noteId, UUID tagId) {
        super(NotesTags.NOTES_TAGS_ENTITY);

        setNoteId(noteId);
        setTagId(tagId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised NotesTagsRecord
     */
    public NotesTagsRecord(NotesTagsEntity value) {
        super(NotesTags.NOTES_TAGS_ENTITY);

        if (value != null) {
            setNoteId(value.getNoteId());
            setTagId(value.getTagId());
            resetChangedOnNotNull();
        }
    }
}
