/*
 * This file is generated by jOOQ.
 */
package ru.onko.model.jooq.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ru.onko.model.jooq.tables.NoteTag;
import ru.onko.model.jooq.tables.pojos.NoteTagEntity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NoteTagRecord extends UpdatableRecordImpl<NoteTagRecord> implements Record3<UUID, String, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.note_tag.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.note_tag.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.note_tag.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.note_tag.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.note_tag.account_id</code>.
     */
    public void setAccountId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.note_tag.account_id</code>.
     */
    public UUID getAccountId() {
        return (UUID) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, String, UUID> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return NoteTag.NOTE_TAG_ENTITY.ID;
    }

    @Override
    public Field<String> field2() {
        return NoteTag.NOTE_TAG_ENTITY.NAME;
    }

    @Override
    public Field<UUID> field3() {
        return NoteTag.NOTE_TAG_ENTITY.ACCOUNT_ID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public UUID component3() {
        return getAccountId();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public UUID value3() {
        return getAccountId();
    }

    @Override
    public NoteTagRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public NoteTagRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public NoteTagRecord value3(UUID value) {
        setAccountId(value);
        return this;
    }

    @Override
    public NoteTagRecord values(UUID value1, String value2, UUID value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NoteTagRecord
     */
    public NoteTagRecord() {
        super(NoteTag.NOTE_TAG_ENTITY);
    }

    /**
     * Create a detached, initialised NoteTagRecord
     */
    public NoteTagRecord(UUID id, String name, UUID accountId) {
        super(NoteTag.NOTE_TAG_ENTITY);

        setId(id);
        setName(name);
        setAccountId(accountId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised NoteTagRecord
     */
    public NoteTagRecord(NoteTagEntity value) {
        super(NoteTag.NOTE_TAG_ENTITY);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setAccountId(value.getAccountId());
            resetChangedOnNotNull();
        }
    }
}
