/*
 * This file is generated by jOOQ.
 */
package ru.onko.model.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.onko.model.jooq.tables.AccessHash;
import ru.onko.model.jooq.tables.Account;
import ru.onko.model.jooq.tables.AccountRoles;
import ru.onko.model.jooq.tables.Article;
import ru.onko.model.jooq.tables.ArticlePhotos;
import ru.onko.model.jooq.tables.FavoriteArticles;
import ru.onko.model.jooq.tables.Note;
import ru.onko.model.jooq.tables.NoteTag;
import ru.onko.model.jooq.tables.NotesSymptoms;
import ru.onko.model.jooq.tables.NotesTags;
import ru.onko.model.jooq.tables.Photo;
import ru.onko.model.jooq.tables.Symptom;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.access_hash</code>.
     */
    public final AccessHash ACCESS_HASH_ENTITY = AccessHash.ACCESS_HASH_ENTITY;

    /**
     * The table <code>public.account</code>.
     */
    public final Account ACCOUNT_ENTITY = Account.ACCOUNT_ENTITY;

    /**
     * The table <code>public.account_roles</code>.
     */
    public final AccountRoles ACCOUNT_ROLES_ENTITY = AccountRoles.ACCOUNT_ROLES_ENTITY;

    /**
     * The table <code>public.article</code>.
     */
    public final Article ARTICLE_ENTITY = Article.ARTICLE_ENTITY;

    /**
     * The table <code>public.article_photos</code>.
     */
    public final ArticlePhotos ARTICLE_PHOTOS_ENTITY = ArticlePhotos.ARTICLE_PHOTOS_ENTITY;

    /**
     * The table <code>public.favorite_articles</code>.
     */
    public final FavoriteArticles FAVORITE_ARTICLES_ENTITY = FavoriteArticles.FAVORITE_ARTICLES_ENTITY;

    /**
     * The table <code>public.note</code>.
     */
    public final Note NOTE_ENTITY = Note.NOTE_ENTITY;

    /**
     * The table <code>public.note_tag</code>.
     */
    public final NoteTag NOTE_TAG_ENTITY = NoteTag.NOTE_TAG_ENTITY;

    /**
     * The table <code>public.notes_symptoms</code>.
     */
    public final NotesSymptoms NOTES_SYMPTOMS_ENTITY = NotesSymptoms.NOTES_SYMPTOMS_ENTITY;

    /**
     * The table <code>public.notes_tags</code>.
     */
    public final NotesTags NOTES_TAGS_ENTITY = NotesTags.NOTES_TAGS_ENTITY;

    /**
     * The table <code>public.photo</code>.
     */
    public final Photo PHOTO_ENTITY = Photo.PHOTO_ENTITY;

    /**
     * The table <code>public.symptom</code>.
     */
    public final Symptom SYMPTOM_ENTITY = Symptom.SYMPTOM_ENTITY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AccessHash.ACCESS_HASH_ENTITY,
            Account.ACCOUNT_ENTITY,
            AccountRoles.ACCOUNT_ROLES_ENTITY,
            Article.ARTICLE_ENTITY,
            ArticlePhotos.ARTICLE_PHOTOS_ENTITY,
            FavoriteArticles.FAVORITE_ARTICLES_ENTITY,
            Note.NOTE_ENTITY,
            NoteTag.NOTE_TAG_ENTITY,
            NotesSymptoms.NOTES_SYMPTOMS_ENTITY,
            NotesTags.NOTES_TAGS_ENTITY,
            Photo.PHOTO_ENTITY,
            Symptom.SYMPTOM_ENTITY
        );
    }
}
