/*
 * This file is generated by jOOQ.
 */
package ru.onko.model.jooq;


import ru.onko.model.jooq.tables.Account;
import ru.onko.model.jooq.tables.AccountRoles;
import ru.onko.model.jooq.tables.Article;
import ru.onko.model.jooq.tables.ArticlePhotos;
import ru.onko.model.jooq.tables.FavoriteArticles;
import ru.onko.model.jooq.tables.Note;
import ru.onko.model.jooq.tables.NoteTag;
import ru.onko.model.jooq.tables.NotesSymptoms;
import ru.onko.model.jooq.tables.NotesTags;
import ru.onko.model.jooq.tables.Photo;
import ru.onko.model.jooq.tables.RefreshToken;
import ru.onko.model.jooq.tables.Symptom;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT_ENTITY = Account.ACCOUNT_ENTITY;

    /**
     * The table <code>public.account_roles</code>.
     */
    public static final AccountRoles ACCOUNT_ROLES_ENTITY = AccountRoles.ACCOUNT_ROLES_ENTITY;

    /**
     * The table <code>public.article</code>.
     */
    public static final Article ARTICLE_ENTITY = Article.ARTICLE_ENTITY;

    /**
     * The table <code>public.article_photos</code>.
     */
    public static final ArticlePhotos ARTICLE_PHOTOS_ENTITY = ArticlePhotos.ARTICLE_PHOTOS_ENTITY;

    /**
     * The table <code>public.favorite_articles</code>.
     */
    public static final FavoriteArticles FAVORITE_ARTICLES_ENTITY = FavoriteArticles.FAVORITE_ARTICLES_ENTITY;

    /**
     * The table <code>public.note</code>.
     */
    public static final Note NOTE_ENTITY = Note.NOTE_ENTITY;

    /**
     * The table <code>public.note_tag</code>.
     */
    public static final NoteTag NOTE_TAG_ENTITY = NoteTag.NOTE_TAG_ENTITY;

    /**
     * The table <code>public.notes_symptoms</code>.
     */
    public static final NotesSymptoms NOTES_SYMPTOMS_ENTITY = NotesSymptoms.NOTES_SYMPTOMS_ENTITY;

    /**
     * The table <code>public.notes_tags</code>.
     */
    public static final NotesTags NOTES_TAGS_ENTITY = NotesTags.NOTES_TAGS_ENTITY;

    /**
     * The table <code>public.photo</code>.
     */
    public static final Photo PHOTO_ENTITY = Photo.PHOTO_ENTITY;

    /**
     * The table <code>public.refresh_token</code>.
     */
    public static final RefreshToken REFRESH_TOKEN_ENTITY = RefreshToken.REFRESH_TOKEN_ENTITY;

    /**
     * The table <code>public.symptom</code>.
     */
    public static final Symptom SYMPTOM_ENTITY = Symptom.SYMPTOM_ENTITY;
}
