/*
 * This file is generated by jOOQ.
 */
package ru.onko.model.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

import lombok.Builder;

/**
 * This class is generated by jOOQ.
 */
@Builder
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccessHashEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private UUID userId;
    private LocalDateTime expiresDate;

    public AccessHashEntity() {}

    public AccessHashEntity(AccessHashEntity value) {
        this.id = value.id;
        this.userId = value.userId;
        this.expiresDate = value.expiresDate;
    }

    public AccessHashEntity(
        UUID id,
        UUID userId,
        LocalDateTime expiresDate
    ) {
        this.id = id;
        this.userId = userId;
        this.expiresDate = expiresDate;
    }

    /**
     * Getter for <code>public.access_hash.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.access_hash.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.access_hash.user_id</code>.
     */
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.access_hash.user_id</code>.
     */
    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>public.access_hash.expires_date</code>.
     */
    public LocalDateTime getExpiresDate() {
        return this.expiresDate;
    }

    /**
     * Setter for <code>public.access_hash.expires_date</code>.
     */
    public void setExpiresDate(LocalDateTime expiresDate) {
        this.expiresDate = expiresDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AccessHashEntity other = (AccessHashEntity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.expiresDate == null) {
            if (other.expiresDate != null)
                return false;
        }
        else if (!this.expiresDate.equals(other.expiresDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.expiresDate == null) ? 0 : this.expiresDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccessHashEntity (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(expiresDate);

        sb.append(")");
        return sb.toString();
    }
}
