/*
 * This file is generated by jOOQ.
 */
package ru.onko.model.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;

import lombok.Builder;

/**
 * This class is generated by jOOQ.
 */
@Builder
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotesTagsEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID noteId;
    private UUID tagId;

    public NotesTagsEntity() {}

    public NotesTagsEntity(NotesTagsEntity value) {
        this.noteId = value.noteId;
        this.tagId = value.tagId;
    }

    public NotesTagsEntity(
        UUID noteId,
        UUID tagId
    ) {
        this.noteId = noteId;
        this.tagId = tagId;
    }

    /**
     * Getter for <code>public.notes_tags.note_id</code>.
     */
    public UUID getNoteId() {
        return this.noteId;
    }

    /**
     * Setter for <code>public.notes_tags.note_id</code>.
     */
    public void setNoteId(UUID noteId) {
        this.noteId = noteId;
    }

    /**
     * Getter for <code>public.notes_tags.tag_id</code>.
     */
    public UUID getTagId() {
        return this.tagId;
    }

    /**
     * Setter for <code>public.notes_tags.tag_id</code>.
     */
    public void setTagId(UUID tagId) {
        this.tagId = tagId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final NotesTagsEntity other = (NotesTagsEntity) obj;
        if (this.noteId == null) {
            if (other.noteId != null)
                return false;
        }
        else if (!this.noteId.equals(other.noteId))
            return false;
        if (this.tagId == null) {
            if (other.tagId != null)
                return false;
        }
        else if (!this.tagId.equals(other.tagId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.noteId == null) ? 0 : this.noteId.hashCode());
        result = prime * result + ((this.tagId == null) ? 0 : this.tagId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("NotesTagsEntity (");

        sb.append(noteId);
        sb.append(", ").append(tagId);

        sb.append(")");
        return sb.toString();
    }
}
