/*
 * This file is generated by jOOQ.
 */
package ru.onko.model.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;

import lombok.Builder;

/**
 * This class is generated by jOOQ.
 */
@Builder
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NoteTagEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String name;
    private UUID accountId;

    public NoteTagEntity() {}

    public NoteTagEntity(NoteTagEntity value) {
        this.id = value.id;
        this.name = value.name;
        this.accountId = value.accountId;
    }

    public NoteTagEntity(
        UUID id,
        String name,
        UUID accountId
    ) {
        this.id = id;
        this.name = name;
        this.accountId = accountId;
    }

    /**
     * Getter for <code>public.note_tag.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.note_tag.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.note_tag.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.note_tag.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.note_tag.account_id</code>.
     */
    public UUID getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>public.note_tag.account_id</code>.
     */
    public void setAccountId(UUID accountId) {
        this.accountId = accountId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final NoteTagEntity other = (NoteTagEntity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!this.accountId.equals(other.accountId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("NoteTagEntity (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(accountId);

        sb.append(")");
        return sb.toString();
    }
}
