/*
 * This file is generated by jOOQ.
 */
package ru.onko.model.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.onko.model.jooq.Keys;
import ru.onko.model.jooq.Public;
import ru.onko.model.jooq.enums.AccountRole;
import ru.onko.model.jooq.tables.records.AccountRolesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountRoles extends TableImpl<AccountRolesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.account_roles</code>
     */
    public static final AccountRoles ACCOUNT_ROLES_ENTITY = new AccountRoles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountRolesRecord> getRecordType() {
        return AccountRolesRecord.class;
    }

    /**
     * The column <code>public.account_roles.account_id</code>.
     */
    public final TableField<AccountRolesRecord, UUID> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.account_roles.account_role</code>.
     */
    public final TableField<AccountRolesRecord, AccountRole> ACCOUNT_ROLE = createField(DSL.name("account_role"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(ru.onko.model.jooq.enums.AccountRole.class), this, "");

    private AccountRoles(Name alias, Table<AccountRolesRecord> aliased) {
        this(alias, aliased, null);
    }

    private AccountRoles(Name alias, Table<AccountRolesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.account_roles</code> table reference
     */
    public AccountRoles(String alias) {
        this(DSL.name(alias), ACCOUNT_ROLES_ENTITY);
    }

    /**
     * Create an aliased <code>public.account_roles</code> table reference
     */
    public AccountRoles(Name alias) {
        this(alias, ACCOUNT_ROLES_ENTITY);
    }

    /**
     * Create a <code>public.account_roles</code> table reference
     */
    public AccountRoles() {
        this(DSL.name("account_roles"), null);
    }

    public <O extends Record> AccountRoles(Table<O> child, ForeignKey<O, AccountRolesRecord> key) {
        super(child, key, ACCOUNT_ROLES_ENTITY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AccountRolesRecord> getPrimaryKey() {
        return Keys.ACCOUNT_ROLES_PKEY;
    }

    @Override
    public List<ForeignKey<AccountRolesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ACCOUNT_ROLES__ACCOUNT_ROLES_ACCOUNT_ID_FKEY);
    }

    private transient Account _account;

    /**
     * Get the implicit join path to the <code>public.account</code> table.
     */
    public Account account() {
        if (_account == null)
            _account = new Account(this, Keys.ACCOUNT_ROLES__ACCOUNT_ROLES_ACCOUNT_ID_FKEY);

        return _account;
    }

    @Override
    public AccountRoles as(String alias) {
        return new AccountRoles(DSL.name(alias), this);
    }

    @Override
    public AccountRoles as(Name alias) {
        return new AccountRoles(alias, this);
    }

    @Override
    public AccountRoles as(Table<?> alias) {
        return new AccountRoles(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountRoles rename(String name) {
        return new AccountRoles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountRoles rename(Name name) {
        return new AccountRoles(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountRoles rename(Table<?> name) {
        return new AccountRoles(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, AccountRole> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super UUID, ? super AccountRole, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super UUID, ? super AccountRole, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
