/*
 * This file is generated by jOOQ.
 */
package ru.onko.model.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.onko.model.jooq.Keys;
import ru.onko.model.jooq.Public;
import ru.onko.model.jooq.tables.records.FavoriteArticlesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FavoriteArticles extends TableImpl<FavoriteArticlesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.favorite_articles</code>
     */
    public static final FavoriteArticles FAVORITE_ARTICLES_ENTITY = new FavoriteArticles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FavoriteArticlesRecord> getRecordType() {
        return FavoriteArticlesRecord.class;
    }

    /**
     * The column <code>public.favorite_articles.account_id</code>.
     */
    public final TableField<FavoriteArticlesRecord, UUID> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.favorite_articles.article_id</code>.
     */
    public final TableField<FavoriteArticlesRecord, UUID> ARTICLE_ID = createField(DSL.name("article_id"), SQLDataType.UUID.nullable(false), this, "");

    private FavoriteArticles(Name alias, Table<FavoriteArticlesRecord> aliased) {
        this(alias, aliased, null);
    }

    private FavoriteArticles(Name alias, Table<FavoriteArticlesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.favorite_articles</code> table reference
     */
    public FavoriteArticles(String alias) {
        this(DSL.name(alias), FAVORITE_ARTICLES_ENTITY);
    }

    /**
     * Create an aliased <code>public.favorite_articles</code> table reference
     */
    public FavoriteArticles(Name alias) {
        this(alias, FAVORITE_ARTICLES_ENTITY);
    }

    /**
     * Create a <code>public.favorite_articles</code> table reference
     */
    public FavoriteArticles() {
        this(DSL.name("favorite_articles"), null);
    }

    public <O extends Record> FavoriteArticles(Table<O> child, ForeignKey<O, FavoriteArticlesRecord> key) {
        super(child, key, FAVORITE_ARTICLES_ENTITY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<FavoriteArticlesRecord> getPrimaryKey() {
        return Keys.FAVORITE_ARTICLES_PKEY;
    }

    @Override
    public List<ForeignKey<FavoriteArticlesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FAVORITE_ARTICLES__FAVORITE_ARTICLES_ACCOUNT_ID_FKEY, Keys.FAVORITE_ARTICLES__FAVORITE_ARTICLES_ARTICLE_ID_FKEY);
    }

    private transient Account _account;
    private transient Article _article;

    /**
     * Get the implicit join path to the <code>public.account</code> table.
     */
    public Account account() {
        if (_account == null)
            _account = new Account(this, Keys.FAVORITE_ARTICLES__FAVORITE_ARTICLES_ACCOUNT_ID_FKEY);

        return _account;
    }

    /**
     * Get the implicit join path to the <code>public.article</code> table.
     */
    public Article article() {
        if (_article == null)
            _article = new Article(this, Keys.FAVORITE_ARTICLES__FAVORITE_ARTICLES_ARTICLE_ID_FKEY);

        return _article;
    }

    @Override
    public FavoriteArticles as(String alias) {
        return new FavoriteArticles(DSL.name(alias), this);
    }

    @Override
    public FavoriteArticles as(Name alias) {
        return new FavoriteArticles(alias, this);
    }

    @Override
    public FavoriteArticles as(Table<?> alias) {
        return new FavoriteArticles(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FavoriteArticles rename(String name) {
        return new FavoriteArticles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FavoriteArticles rename(Name name) {
        return new FavoriteArticles(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FavoriteArticles rename(Table<?> name) {
        return new FavoriteArticles(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super UUID, ? super UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super UUID, ? super UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
