/*
 * This file is generated by jOOQ.
 */
package ru.onko.model.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.onko.model.jooq.Keys;
import ru.onko.model.jooq.Public;
import ru.onko.model.jooq.tables.records.NoteTagRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NoteTag extends TableImpl<NoteTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.note_tag</code>
     */
    public static final NoteTag NOTE_TAG_ENTITY = new NoteTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NoteTagRecord> getRecordType() {
        return NoteTagRecord.class;
    }

    /**
     * The column <code>public.note_tag.id</code>.
     */
    public final TableField<NoteTagRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.note_tag.name</code>.
     */
    public final TableField<NoteTagRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.note_tag.account_id</code>.
     */
    public final TableField<NoteTagRecord, UUID> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.UUID.nullable(false), this, "");

    private NoteTag(Name alias, Table<NoteTagRecord> aliased) {
        this(alias, aliased, null);
    }

    private NoteTag(Name alias, Table<NoteTagRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.note_tag</code> table reference
     */
    public NoteTag(String alias) {
        this(DSL.name(alias), NOTE_TAG_ENTITY);
    }

    /**
     * Create an aliased <code>public.note_tag</code> table reference
     */
    public NoteTag(Name alias) {
        this(alias, NOTE_TAG_ENTITY);
    }

    /**
     * Create a <code>public.note_tag</code> table reference
     */
    public NoteTag() {
        this(DSL.name("note_tag"), null);
    }

    public <O extends Record> NoteTag(Table<O> child, ForeignKey<O, NoteTagRecord> key) {
        super(child, key, NOTE_TAG_ENTITY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<NoteTagRecord> getPrimaryKey() {
        return Keys.NOTE_TAG_PKEY;
    }

    @Override
    public List<ForeignKey<NoteTagRecord, ?>> getReferences() {
        return Arrays.asList(Keys.NOTE_TAG__NOTE_TAG_ACCOUNT_ID_FKEY);
    }

    private transient Account _account;

    /**
     * Get the implicit join path to the <code>public.account</code> table.
     */
    public Account account() {
        if (_account == null)
            _account = new Account(this, Keys.NOTE_TAG__NOTE_TAG_ACCOUNT_ID_FKEY);

        return _account;
    }

    @Override
    public NoteTag as(String alias) {
        return new NoteTag(DSL.name(alias), this);
    }

    @Override
    public NoteTag as(Name alias) {
        return new NoteTag(alias, this);
    }

    @Override
    public NoteTag as(Table<?> alias) {
        return new NoteTag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NoteTag rename(String name) {
        return new NoteTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NoteTag rename(Name name) {
        return new NoteTag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NoteTag rename(Table<?> name) {
        return new NoteTag(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super UUID, ? super String, ? super UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super UUID, ? super String, ? super UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
