/*
 * This file is generated by jOOQ.
 */
package ru.onko.model.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.onko.model.jooq.Keys;
import ru.onko.model.jooq.Public;
import ru.onko.model.jooq.tables.records.NotesSymptomsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotesSymptoms extends TableImpl<NotesSymptomsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.notes_symptoms</code>
     */
    public static final NotesSymptoms NOTES_SYMPTOMS_ENTITY = new NotesSymptoms();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NotesSymptomsRecord> getRecordType() {
        return NotesSymptomsRecord.class;
    }

    /**
     * The column <code>public.notes_symptoms.note_id</code>.
     */
    public final TableField<NotesSymptomsRecord, UUID> NOTE_ID = createField(DSL.name("note_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.notes_symptoms.symptom_id</code>.
     */
    public final TableField<NotesSymptomsRecord, UUID> SYMPTOM_ID = createField(DSL.name("symptom_id"), SQLDataType.UUID.nullable(false), this, "");

    private NotesSymptoms(Name alias, Table<NotesSymptomsRecord> aliased) {
        this(alias, aliased, null);
    }

    private NotesSymptoms(Name alias, Table<NotesSymptomsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.notes_symptoms</code> table reference
     */
    public NotesSymptoms(String alias) {
        this(DSL.name(alias), NOTES_SYMPTOMS_ENTITY);
    }

    /**
     * Create an aliased <code>public.notes_symptoms</code> table reference
     */
    public NotesSymptoms(Name alias) {
        this(alias, NOTES_SYMPTOMS_ENTITY);
    }

    /**
     * Create a <code>public.notes_symptoms</code> table reference
     */
    public NotesSymptoms() {
        this(DSL.name("notes_symptoms"), null);
    }

    public <O extends Record> NotesSymptoms(Table<O> child, ForeignKey<O, NotesSymptomsRecord> key) {
        super(child, key, NOTES_SYMPTOMS_ENTITY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<NotesSymptomsRecord> getPrimaryKey() {
        return Keys.NOTES_SYMPTOMS_PKEY;
    }

    @Override
    public List<ForeignKey<NotesSymptomsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.NOTES_SYMPTOMS__NOTES_SYMPTOMS_NOTE_ID_FKEY, Keys.NOTES_SYMPTOMS__NOTES_SYMPTOMS_SYMPTOM_ID_FKEY);
    }

    private transient Note _note;
    private transient Symptom _symptom;

    /**
     * Get the implicit join path to the <code>public.note</code> table.
     */
    public Note note() {
        if (_note == null)
            _note = new Note(this, Keys.NOTES_SYMPTOMS__NOTES_SYMPTOMS_NOTE_ID_FKEY);

        return _note;
    }

    /**
     * Get the implicit join path to the <code>public.symptom</code> table.
     */
    public Symptom symptom() {
        if (_symptom == null)
            _symptom = new Symptom(this, Keys.NOTES_SYMPTOMS__NOTES_SYMPTOMS_SYMPTOM_ID_FKEY);

        return _symptom;
    }

    @Override
    public NotesSymptoms as(String alias) {
        return new NotesSymptoms(DSL.name(alias), this);
    }

    @Override
    public NotesSymptoms as(Name alias) {
        return new NotesSymptoms(alias, this);
    }

    @Override
    public NotesSymptoms as(Table<?> alias) {
        return new NotesSymptoms(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NotesSymptoms rename(String name) {
        return new NotesSymptoms(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NotesSymptoms rename(Name name) {
        return new NotesSymptoms(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NotesSymptoms rename(Table<?> name) {
        return new NotesSymptoms(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super UUID, ? super UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super UUID, ? super UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
