/*
 * This file is generated by jOOQ.
 */
package ru.onko.model.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.onko.model.jooq.Keys;
import ru.onko.model.jooq.Public;
import ru.onko.model.jooq.tables.records.PhotoRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Photo extends TableImpl<PhotoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.photo</code>
     */
    public static final Photo PHOTO_ENTITY = new Photo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PhotoRecord> getRecordType() {
        return PhotoRecord.class;
    }

    /**
     * The column <code>public.photo.id</code>.
     */
    public final TableField<PhotoRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.photo.name</code>.
     */
    public final TableField<PhotoRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    private Photo(Name alias, Table<PhotoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Photo(Name alias, Table<PhotoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.photo</code> table reference
     */
    public Photo(String alias) {
        this(DSL.name(alias), PHOTO_ENTITY);
    }

    /**
     * Create an aliased <code>public.photo</code> table reference
     */
    public Photo(Name alias) {
        this(alias, PHOTO_ENTITY);
    }

    /**
     * Create a <code>public.photo</code> table reference
     */
    public Photo() {
        this(DSL.name("photo"), null);
    }

    public <O extends Record> Photo(Table<O> child, ForeignKey<O, PhotoRecord> key) {
        super(child, key, PHOTO_ENTITY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PhotoRecord> getPrimaryKey() {
        return Keys.PHOTO_PKEY;
    }

    @Override
    public List<UniqueKey<PhotoRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PHOTO_NAME_KEY);
    }

    @Override
    public Photo as(String alias) {
        return new Photo(DSL.name(alias), this);
    }

    @Override
    public Photo as(Name alias) {
        return new Photo(alias, this);
    }

    @Override
    public Photo as(Table<?> alias) {
        return new Photo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Photo rename(String name) {
        return new Photo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Photo rename(Name name) {
        return new Photo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Photo rename(Table<?> name) {
        return new Photo(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super UUID, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super UUID, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
